### ISSUE TITLE
New Release?

### ISSUE THREAD

**Issue by strigona-worksight** [shelfio/es-painless-fields#70]
I see that dependencies are being automatically updated, are there any plans to cut a new release with these updates?

**Comment by vladgolubev** [comment]
Hey Simon!

Sure, thanks for bringing this up! I've just published a new release [v 0.5.1](https://github.com/shelfio/es-painless-fields/releases/tag/v0.5.1) with all the dependencies updates!

**Comment by strigona-worksight** [comment]
Thank you!
